### ISSUE TITLE
Consider disabling signing when experimenting

### ISSUE THREAD

**Issue by FauxFaux** [Timmmm/autorebase#3]
The `commit.gpgsign` option adds 300ms+ of latency to each commit, making a large rebase take minutes instead of seconds.

Can the tool toggle it off? Explicitly opt out?

I'd like it on for the final rebase of the branch, as the commits should be signed on the final branch, but there's no need for it to be on (slowing everything down) while messing around?

**Comment by Timmmm** [comment]
Ah yeah we should definitely turn it off for the rebase that figures out where conflicts are. I think you just need to add something like `-c commit.gpgsign=false` on [this line](https://github.com/Timmmm/autorebase/blob/master/src/lib.rs#L498) (not too sure though; I have never used commit signing).

More difficult to turn it off for the slow method, but given that is not the default it probably doesn't matter.

PR welcome! :-)

Also 300ms for signing seems crazy!
