### ISSUE TITLE
Update default branch name

### ISSUE THREAD

**Issue by simonsan** [Timmmm/autorebase#6]
Github's default branch name is `main` for new repositories since around 3 years: https://github.com/github/renaming

Might be worth to change this as well in `autorebase` to account for changes in the ecosystem?

**Comment by Timmmm** [comment]
Almost all the repos I use still use `master`, and thankfully you can still opt out of `main` in settings:

![image](https://github.com/Timmmm/autorebase/assets/376842/5144b1c0-2584-4c51-a866-1386e2e65061)

However I do now have to use one repo that uses `main` - which is very annoying - so I was mulling a solution. I think what I will do is make it read `init.defaultBranch` from Git config and use that if it is set, or `master` if it isn't. That allows global and per-repo settings and should work in most cases.

**Comment by Timmmm** [comment]
We'll have to disagree about the merits of fighting imaginary racism... but anyway I have made a new release that should respect `init.defaultBranch`. Just run `git config [--global] init.defaultBranch main` and it should use `main` henceforth.

Let me know if you have any problems!
